ninoseki/ioc-extractor

README.md
src/aux/auxiliary.ts
src/spec/auxiliary.spec.ts
src/spec/index.spec.ts

Add following refang techniques (include #16).
| Techniques   | Defanged                    | Refanged                  |
|:-------------|:----------------------------|:--------------------------|
| `\.`  => `.` | `example\.com`              | `example.com`             |
| `[/]` => `/` | `http://example.com[/]path` | `http://example.com/path` |
| `[:]` => `:` | `http[:]//example.com`      | `http://example.com`      |

Improve refang feature

---

README.md
src/aux/regexs.ts
src/index.ts
src/spec/index.spec.ts
src/spec/regexs.spec.ts

feat: add Tracker type IOC support

---

src/aux/extractor.ts
src/index.ts

Breakdown extracting tasks into each method

refactor: refactor architecture

---

package.json
src/aux/auxiliary.ts
src/aux/extractor.ts
src/aux/regexs.ts
src/aux/tlds.ts
src/bin/ioc-extractor.ts
src/index.ts
src/spec/auxiliary.spec.ts
src/spec/index.spec.ts
src/spec/regexs.spec.ts

Fix ESLint erros and format by Prettier

refactor: fix ESLint erros & format by prettier

---

README.md
src/aux/extractor.ts
src/aux/regexs.ts
src/index.ts
src/spec/auxiliary.spec.ts
src/spec/index.spec.ts
src/spec/regexs.spec.ts

Flatten the attributes for more easy-to-use

refactor: flatten the attributes

---

.travis.yml
README.md

Migrate to travis-ci.com from travis-ci.org

chore: migrate to travis-ci.com

---

README.md

Migrate to CodeFactor from CodeClimate & Codacy

chore: migrate to CodeFactor 

---

src/aux/regexes.ts
src/spec/regexes.spec.ts

Renew regexps to improve accuracy & maintainability

refactor: renew regexps

---

.eslintrc
src/bin/ioc-extractor.ts
src/spec/index.spec.ts
src/spec/regexes.spec.ts
src/spec/sitx2.spec.ts
src/stix2/stix2.ts

Update ESLint setting & autofix warnings/errors

refactor: update ESLint setting

---

.travis.yml

Support node v14 & drop v12 support

ci: support node v14

---

README.md
src/aux/auxiliary.ts
src/bin/ioc-extractor.ts
src/index.ts
src/spec/auxiliary.spec.ts
src/spec/index.spec.ts
src/spec/sitx2.spec.ts

refactor: rename function names

---

package-lock.json
package.json
src/aux/auxiliary.ts

Use array-unique to improve performance

refactor: use array-unique

---

src/index.ts

Use extractIOC instead of getIOC

fix: use extractIOC

---

src/aux/regexes.ts
src/spec/regexes.spec.ts

fix: update regexp for URL

---

package-lock.json
package.json
src/bin/ioc-extractor.ts
src/index.ts
src/spec/index.spec.ts
src/workers/extractor.ts

Add async version of methods to improve performance by using threads

feat: add async version of methods

---

src/aux/regexes.ts
src/spec/regexes.spec.ts

Change to check the length of a label more strictly

refactor: change to check the label length

---

src/aux/extractor.ts
src/aux/regexes.ts
src/index.ts
src/spec/index.spec.ts
src/spec/regexes.spec.ts
src/workers/extractor.ts

Add enableIDN option to control whether extract IDNs or not

feat: add enableIDN option

---

src/aux/regexes.ts
src/spec/regexes.spec.ts

Make possible to extract punycode domain

fix: enable to extract a domain starts with xn--

---

README.md
src/aux/extractor.ts
src/aux/regexes.ts
src/bin/ioc-extractor.ts
src/index.ts
src/spec/index.spec.ts
src/workers/extractor.ts

Add "strictTLD" option to control whether validate the TLD strictly or not

feat: add strictTLD option

---

src/aux/regexpes.ts
src/spec/regexpes.spec.ts

fix: update regexp for email local-part

---

package-lock.json
package.json
src/bin/ioc-extractor.ts

fix: revert get-stdin to v8

---

package-lock.json
package.json
src/aux/extractor.ts
src/aux/regexpes.ts
src/bin/ioc-extractor.ts
src/index.ts
src/stix2/stix2.ts

Use [tsup](https://github.com/egoist/tsup) for the dual packaging (support both CJS and MJS)

refactor: use tsup for dual package

---

.github/workflows/test.yml

Update GitHub Actions actions.

ci: update actions

---

package.json

refactor: include src directory

---

package.json

refactor: set prepack [skip ci]

---

spec/index.spec.ts
spec/regexps.spec.ts

Use `toEqual()` for assertions

refactor: use toEqual()

---

src/aux/regexps.ts

refactor: split regexp into chunks

---

spec/aux/domain.spec.ts
src/aux/domain.ts

fix: fix #334

---

README.md
spec/index.spec.ts
src/bin/ioc-extractor.ts
src/index.ts
src/types.ts

Add `only` option (this idea comes from @yssrku's fork)

feat: add only option
